sudo: required
services:
  - docker


before_install:
  - docker build -t moubouhou/docker-react -f Dockerfile.dev .

script:
  - docker run moubouhou/docker-react npm run test -- --env=jsdom --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-travis-env"
  bucket_name: "elasticbeanstalk-eu-west-3-655434543225"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
