sudo: required
services:
  - docker


before_install:
  - docker build -t moubouhou/docker-react -f Dockerfile.dev .

script:
  - docker run moubouhou/docker-react npm run test -- --env=jsdom --watchAll=false --coverage